### PR TITLE
Fix use with bash process substitution and other special files

### PR DESCRIPTION
**Pull request by joshkel**
Using os.path.isfile fails on special files like /dev/fd/N, which bash
uses for process substitution.  It's probably better to assume that
anything that isn't a directory can be treated like a file.

### CODE REVIEW

**Comment by joshkel** [comment]
I didn't realize that #81 already addresses this. I think my PR is a little bit cleaner, but I could be wrong.

**Comment by jeffkaufman** [comment]
Sorry for taking so long to review this!

If you resolve the merge conflicts I'll merge it

**Comment by joshkel** [comment]
I rebased off of master and added a test.

However, I noticed that my changes introduce a conflict of sorts with #91. After my changes, icdiff treats /dev/null the same as a regular file, so my icdiff's behavior is always the same as #91's behavior with `--show-add-rm`.

How would you like me to handle this? I can special case reading from `/dev/null` to get the previous behavior, but personally, I think the new behavior is the desired behavior (allowing reading from `/dev/null` to act the same as for any regular file seems more consistent with Unix in general, and it would thus work with `git difftool` out of the box). However, I'm happy to implement whichever approach you like.

**Comment by jeffkaufman** [comment]
How about we remove `--show-add-rm` and get the new behavior the whole time?

(We haven't done a release with `--show-add-rm` so I don't think we need to keep backwards compatibility there in terms of keeping supporting arguments)

**Comment by joshkel** [comment]
Done. Sorry for the delay.

**Pull request merged**
