### PR TITLE
Add flake8 as a linter

### PR DESCRIPTION
**Pull request by aneeshusa**
Fix a typo and add flake8 as a linter to catch future typos.

### CODE REVIEW

**Comment by lurch** [comment]
This needs to be rebased.

**Comment by aneeshusa** [comment]
Rebased, thanks for the reminder @lurch.

**Comment by lurch** [comment]
Looks like you might need to add `pip install -r requirements-dev.txt` to `.travis.yml` in order to get the Travis CI tests passing?

**Comment by aneeshusa** [comment]
Done on both counts, Travis is green now.

**Comment by aneeshusa** [comment]
Thanks for reviewing and all of icdiff by the way! I can't believe I've been benefiting from it for over 2 years now, thanks for writing it :)

**Pull request merged**
