### PR TITLE
icdiff works as python API call

### PR DESCRIPTION
**Pull request by vnitinv**
``` python
from icdiff import diff
diff('/var/tmp/xxx.txt', '/var/tmp/xxx.txt')
```

pep8 cleanup
added gitignore
Fix #75

### CODE REVIEW

**Comment by vnitinv** [comment]
icdiff version 1.9.1 released to PyPI
https://pypi.python.org/pypi/icdiff/1.9.1

**Comment by lurch** [comment]
IMHO this PR is trying to do too much all at once. I think you'd be more likely to get these changes accepted if your broke it up into separate smaller PRs.

**Comment by jeffkaufman** [comment]
Agreed with lurch: if you have a change you still want me to make, please give me several minimal diffs.

**Comment by vnitinv** [comment]
@jeffkaufman I will try to send a pull request with single commit.

**Comment by lurch** [comment]
@vnitinv To clarify - we're not simply asking for one PR with a single commit, but instead we're asking for  separate PRs implementing each of the things you've listed in your first message, i.e.:
One PR for "icdiff works as python API call"
A separate PR for "pep8 cleanup"
A separate PR for "added gitignore"
And a separate PR for "Fix #75" (whatever that means :wink: )

Does that make sense? This makes it easier for @jeffkaufman to see what changes are needed for each separate feature, and makes it easier to discuss / analyse / approve each feature in isolation.

**Pull request closed without merging**
