### PR TITLE
resolves icdiff module usage

### PR DESCRIPTION
**Pull request by vnitinv**
Now we can do:

``` python
from icdiff import diff
diff('/var/tmp/xxx.txt', '/var/tmp/xxx.txt')
```

### CODE REVIEW

**Comment by jeffkaufman** [comment]
The problem with this patch is that installing `icdiff` is `/usr/local/bin/icdiff` will stop working.

**Comment by vnitinv** [comment]
@jeffkaufman I dont see any issue

[root@gls-esx6-vm16 ~]# which icdiff
/usr/bin/which: **no icdiff** in (/usr/local/rvm/gems/ruby-2.2.2/bin:/usr/local/rvm/gems/ruby-2.2.2@global/bin:/usr/local/rvm/rubies/ruby-2.2.2/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/rvm/bin:/root/bin)

[root@gls-esx6-vm16 ~]# pip install git+https://github.com/vnitinv/icdiff
Collecting git+https://github.com/vnitinv/icdiff
  Cloning https://github.com/vnitinv/icdiff to /tmp/pip-H6JjNW-build
Installing collected packages: icdiff
  Running setup.py install for icdiff ... done
Successfully installed icdiff-1.8.5
[root@gls-esx6-vm16 ~]# which icdiff
/usr/local/bin/icdiff

image

**Comment by jeffkaufman** [comment]
Right now our primary installation method is people running:

```
curl -s https://raw.githubusercontent.com/jeffkaufman/icdiff/release-1.8.1/icdiff \
  | sudo tee /usr/local/bin/icdiff > /dev/null \
  && sudo chmod ugo+rx /usr/local/bin/icdiff
```

It looks to me like this PR will break that?

**Comment by peanball** [comment]
This commit breaks recursive diff because the option argument was changed in one place but not all of them.

This is also the version currently available via PyPi and is broken (https://pypi.python.org/pypi/icdiff). I would suggest taking this broken build down from PyPi until Jeff has accepted the pull request. The entry there just says Jeff Kaufman and I guess he didn't publish such a broken version there!

**Comment by vnitinv** [comment]
@peanball We should rather fix the issue in place of bringing it down from PyPI. The code base in PyPI might have some (or many) bugs, but by putting it in PyPI it made life easier for many.

Anyways the onus is with Jeff if he want to remove it from PyPI.

**Comment by vnitinv** [comment]
Will send a fresh pull request.

**Pull request closed without merging**
