### PR TITLE
Diff user input passed with `-i` flag

### PR DESCRIPTION
**Pull request by kevinlitchfield**

### CODE REVIEW

**Comment by jeffkaufman** [comment]
I'm not sure `icdiff -i "foo" bar"` is enough of an improvement over `icdiff <(echo "foo") <(echo "bar")` to be worth adding?

(See http://stackoverflow.com/questions/454427/bash-string-difference for example)

**Comment by kevinlitchfield** [comment]
It's not an improvement in functionality, but it's conceptually simpler. If someone doesn't know what process substitution is, they won't realize it's possible to use icdiff to diff two strings without putting them in files first. And if someone who may or may not know what process substitution is asks me how to diff two strings on the command line, it's easier to reply, "Just do `icdiff -i first_string second_string`" instead of replying, "Just do `icdiff <(echo "first_string") <(echo "second_string")`" and then potentially having to educate them on process substitution or tell them "don't worry about the parens and less than signs."

Just my two cents!

**Comment by jeffkaufman** [comment]
I agree it's simpler to explain, but (currently) I think it's not enough simpler to be worth the extra option and code complexity?

Are there any other other diff tools that support an option like this?

**Comment by kevinlitchfield** [comment]
OK, that's fair. I'd also make the argument that there's an ergonomic benefit -- to diff two strings, you can paste them immediately in sequence after typing `icdiff -i` if you don't need quotes, rather than typing `<(echo `, pasting one, typing `) <(echo `, pasting the other, then typing `)`. Probably saves a few seconds each time, but of course it's a judgment call whether that's worth it.

Not sure whether there are other diff tools that support an option like this, did a quick search that didn't turn up anything. From a UX perspective, I think the comparison here is to something like Diff Checker.

**Comment by lurch** [comment]
I'd be inclined to agree - unless other diff tools offer this functionality, it probably doesn't make sense to add this to icdiff. Especially as `diff` already has a `-i` option, which means something else:
```
  -i, --ignore-case               ignore case differences in file contents
```

**Comment by jeffkaufman** [comment]
closing this; I don't think `-i` is a good thing to add

**Pull request closed without merging**
