### PR TITLE
Fix: Fullwidth characters should get width 2

### PR DESCRIPTION
**Pull request by adah1972**
Wide characters (like "。") are already handled by the current code, but fullwidth characters (like "，") are not.

### CODE REVIEW

**Comment by jeffkaufman** [comment]
Thanks!  Could you add a test?

**Comment by adah1972** [comment]
I updated the tests so that the old icdiff version would fail on tests. You could also check the difference yourself by running:

```sh
./icdiff tests/input-1.txt tests/input-2.txt
```

**Review by jeffkaufman — APPROVED** [review]

**Comment by jeffkaufman** [comment]
Thanks!

**Comment by jeffkaufman** [comment]
Released in 2.0.6

**Pull request merged**
